### ISSUE TITLE
代码有点乱啊，表示看不太懂，呜呜。。。。

### ISSUE THREAD

**Issue by gengyanlei** [cswluo/CrossX#3]

**Comment by qgking** [comment]
> _No description provided._

absolutely

**Comment by gengyanlei** [comment]
不过 还是看完了一遍，只是主函数部分稍微乱一些，哈哈。静下心来，就还好了。

**Comment by morning4346** [comment]
想问以下，有人用resnet50跑cubird，能达到作者的精度87.7%吗？

**Comment by morning4346** [comment]
我使用resnet50做backbone跑cubird只达到了87.5%,你们跑到87.7%了吗？

**Comment by gengyanlei** [comment]
没有，不过可以了，差距很微小，我用它跑了其它的数据集效果不是很好。

**Comment by RoryShao** [comment]
> 我使用resnet50做backbone跑cubird只达到了87.5%,你们跑到87.7%了吗？

请问跑了多少epoch?貌似起点很低。
